services:
  booksearcher:
    image: gaodes/booksearcher:latest
    container_name: booksearcher
    volumes:
      - ./.env:/app/.env:ro
    environment:
      - TZ=Europe/Bucharest
      - ENV=/etc/profile.d/booksearcher.sh
    stdin_open: true
    tty: true
    restart: unless-stopped
