services:
  booksearcher:
    image: gaodes/booksearcher:latest
    container_name: booksearcher
    network_mode: host
    volumes:
      - ./cache:/app/cache  # For persistent cache
      - ./config:/app/config  # For persistent configuration
    environment:
      - TZ=Europe/Bucharest
      # These values will be used to create the initial config.yaml if it doesn't exist
      - PROWLARR_URL=http://your-prowlarr-url:9696
      - API_KEY=your-prowlarr-api-key
      - CACHE_MAX_AGE=168  # 7 days in hours
      - CACHE_MAX_SIZE=100  # Size in MB
      - CACHE_MAX_ENTRIES=100  # Maximum number of cached searches
    restart: unless-stopped
