services:
  booksearcher:
    build: .
    container_name: booksearcher
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env:ro
    environment:
      - TZ=Europe/Bucharest
    stdin_open: true
    tty: true
